services:
  team-docs:
    build:
      context: .
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://mazumder:1234@team-docs-postgres:5432/team-docs?schema=public
      - NEXTAUTH_URL=http://localhost:3000
      - AUTH_SECRET=EhWUf2pHNDJ3icR25TyjHMpV/Irdvrbhr3TGBQkLN1o=

      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
    volumes:
      # - .:/app:cached
      - .:/app
      - /app/.next
    ports:
      - "3000:3000"
    depends_on:
      - team-docs-postgres
    networks:
      - postgres-network

  team-docs-postgres:
    image: postgres:16
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: mazumder
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: team-docs
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - postgres-network

networks:
  postgres-network:
    driver: bridge

volumes:
  postgres_data:
